### ISSUE TITLE
Implement Julia standard library IO backend

### ISSUE THREAD

**Issue by PhilipFackler** [ORNL/RIOPA.jl#28]

**Comment by PhilipFackler** [comment]
@williamfgc , any thoughts what we could call this in the YAML file? Like "JuliaSTL"?

**Comment by williamfgc** [comment]
The resulting struct from `open` is `Base.IOStream`, we could call it IOStream and refer to the Julia [docs](https://docs.julialang.org/en/v1/base/io-network/#Base.IOStream). Just my 2 cents.

**Comment by PhilipFackler** [comment]
Need to look into controlling buffer size.
